version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER:'postgres'
      - POSTGRES_PASSWORD:'123456'
      - POSTGRES_DB:'db'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/e-sportsBet
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres-data:
    driver: local
