POSTGRES_USER: 'postgres'
POSTGRES_PASSWORD: '123456'
POSTGRES_HOST: 'db'
MAILGUN_DOMAIN: 'sandboxfc5503da5eba409abe32d13cb42cd76e.mailgun.org'
MAILGUN_SMTP_LOGIN: 'postmaster@sandboxfc5503da5eba409abe32d13cb42cd76e.mailgun.org'
MAILGUN_SMTP_PASSWORD: '4d315566b8bc4e0e0adcf70bf18a3ee7'
MAILGUN_SMTP_SERVER: 'smtp.mailgun.org'
MAILGUN_SMTP_PORT: '587'
FACEBOOK_ID: ‘’
FACEBOOK_SECRET: ‘’
